USE ROLE ACCOUNTADMIN;
USE WAREHOUSE PULSEOPS_WH;
USE DATABASE PULSEOPS;
USE SCHEMA CORE;

-- =========================================================
-- PulseOps
-- WINDOWED_METRICS validation
-- =========================================================

SELECT COUNT(*) AS WINDOW_ROWS
FROM PULSEOPS.CORE.WINDOWED_METRICS;


-- Sample windows
SELECT *
FROM PULSEOPS.CORE.WINDOWED_METRICS
ORDER BY WINDOW_START DESC
LIMIT 20;


-- Inspect severity activity inside windows
SELECT
    COUNT(*) AS TOTAL_WINDOWS,

    COUNT_IF(ERROR_COUNT > 0)
        AS WINDOWS_WITH_ERRORS,

    COUNT_IF(WARN_COUNT > 0)
        AS WINDOWS_WITH_WARNINGS,

    MAX(ERROR_COUNT)
        AS MAX_ERRORS_IN_WINDOW,

    MAX(WARN_COUNT)
        AS MAX_WARNINGS_IN_WINDOW

FROM PULSEOPS.CORE.WINDOWED_METRICS;


-- Windows that would be interesting to the original
-- severity-based detector
SELECT
    BLOCK_ID,
    WINDOW_START,
    WINDOW_END,
    EVENT_COUNT,
    ERROR_COUNT,
    WARN_COUNT
FROM PULSEOPS.CORE.WINDOWED_METRICS
WHERE ERROR_COUNT > 0
   OR WARN_COUNT > 0
ORDER BY ERROR_COUNT DESC,
         WARN_COUNT DESC;


-- Distribution of event volumes
SELECT
    MIN(EVENT_COUNT) AS MIN_EVENTS,
    AVG(EVENT_COUNT) AS AVG_EVENTS,
    MEDIAN(EVENT_COUNT) AS MEDIAN_EVENTS,
    MAX(EVENT_COUNT) AS MAX_EVENTS,
    STDDEV(EVENT_COUNT) AS STDDEV_EVENTS
FROM PULSEOPS.CORE.WINDOWED_METRICS;