SELECT COUNT(*) AS TOTAL_ROWS
FROM PULSEOPS.CORE.GROUND_TRUTH_LABELS;

SELECT
    LABEL,
    COUNT(*) AS COUNT
FROM PULSEOPS.CORE.GROUND_TRUTH_LABELS
GROUP BY LABEL
ORDER BY LABEL;

SELECT
    COUNT_IF(BLOCK_ID IS NULL OR TRIM(BLOCK_ID)='') AS BLANK_BLOCK_IDS,
    COUNT_IF(LABEL NOT IN ('Normal','Anomaly')) AS UNEXPECTED_LABELS
FROM PULSEOPS.CORE.GROUND_TRUTH_LABELS;