WITH block_features AS (
    SELECT
        BLOCK_ID,
        COUNT(*) AS TOTAL_EVENTS,
        COUNT(DISTINCT COMPONENT) AS UNIQUE_COMPONENTS,
        COUNT(DISTINCT MESSAGE) AS UNIQUE_MESSAGES,
        DATEDIFF(
            'second',
            MIN(EVENT_TIME),
            MAX(EVENT_TIME)
        ) AS LIFETIME_SECONDS
    FROM PULSEOPS.CORE.RAW_LOG_EVENTS
    WHERE BLOCK_ID IS NOT NULL
      AND EVENT_TIME IS NOT NULL
    GROUP BY BLOCK_ID
)

SELECT
    g.LABEL,

    COUNT(*) AS BLOCKS,

    ROUND(AVG(f.TOTAL_EVENTS), 2)
        AS AVG_TOTAL_EVENTS,

    ROUND(AVG(f.UNIQUE_COMPONENTS), 2)
        AS AVG_UNIQUE_COMPONENTS,

    ROUND(AVG(f.UNIQUE_MESSAGES), 2)
        AS AVG_UNIQUE_MESSAGES,

    ROUND(AVG(f.LIFETIME_SECONDS), 2)
        AS AVG_LIFETIME_SECONDS,

    MEDIAN(f.LIFETIME_SECONDS)
        AS MEDIAN_LIFETIME_SECONDS

FROM block_features f

JOIN PULSEOPS.CORE.GROUND_TRUTH_LABELS g
    ON f.BLOCK_ID = g.BLOCK_ID

GROUP BY g.LABEL;