SELECT
    (SELECT COUNT(*)
     FROM PULSEOPS.CORE.RAW_LOG_EVENTS) AS RAW_ROWS,

    (SELECT COUNT(*)
     FROM PULSEOPS.CORE.WINDOWED_METRICS) AS WINDOW_ROWS,

    (SELECT COUNT(*)
     FROM PULSEOPS.CORE.INCIDENTS) AS INCIDENT_ROWS,

    (SELECT COUNT(DISTINCT BLOCK_ID)
     FROM PULSEOPS.CORE.RAW_LOG_EVENTS) AS UNIQUE_BLOCKS;