USE ROLE ACCOUNTADMIN;
USE WAREHOUSE PULSEOPS_WH;
USE DATABASE PULSEOPS;
USE SCHEMA CORE;

SELECT
    (SELECT COUNT(*)
     FROM RAW_LOG_EVENTS) AS RAW_ROWS,

    (SELECT COUNT(*)
     FROM WINDOWED_METRICS) AS WINDOW_ROWS,

    (SELECT COUNT(*)
     FROM INCIDENTS) AS INCIDENT_ROWS,

    (SELECT COUNT(DISTINCT BLOCK_ID)
     FROM RAW_LOG_EVENTS) AS UNIQUE_BLOCKS;