-- =========================================================
-- SECTION 1: SET CONTEXT
-- =========================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE PULSEOPS_WH;
USE DATABASE PULSEOPS;
USE SCHEMA CORE;


-- =========================================================
-- SECTION 2: CREATE COMPONENT WINDOW ACTIVITY
-- =========================================================

CREATE OR REPLACE TEMP VIEW COMPONENT_WINDOW_ACTIVITY AS
SELECT
    DATE_TRUNC('MINUTE', EVENT_TIME) AS WINDOW_START,
    DATEADD(
        'MINUTE',
        1,
        DATE_TRUNC('MINUTE', EVENT_TIME)
    ) AS WINDOW_END,
    COMPONENT,
    COUNT(*) AS EVENT_COUNT,
    COUNT_IF(LEVEL = 'ERROR') AS ERROR_COUNT,
    COUNT_IF(LEVEL = 'WARN') AS WARN_COUNT
FROM PULSEOPS.CORE.RAW_LOG_EVENTS
WHERE EVENT_TIME IS NOT NULL
  AND COMPONENT IS NOT NULL
GROUP BY
    DATE_TRUNC('MINUTE', EVENT_TIME),
    COMPONENT;


-- =========================================================
-- SECTION 3: INTEGRITY CHECK
-- =========================================================

SELECT
    (SELECT COUNT(*)
     FROM PULSEOPS.CORE.RAW_LOG_EVENTS
     WHERE EVENT_TIME IS NOT NULL
       AND COMPONENT IS NOT NULL) AS RAW_ELIGIBLE_EVENTS,

    (SELECT SUM(EVENT_COUNT)
     FROM COMPONENT_WINDOW_ACTIVITY) AS AGGREGATED_EVENTS,

    (SELECT COUNT(*)
     FROM PULSEOPS.CORE.RAW_LOG_EVENTS
     WHERE EVENT_TIME IS NOT NULL
       AND COMPONENT IS NOT NULL)
    -
    (SELECT SUM(EVENT_COUNT)
     FROM COMPONENT_WINDOW_ACTIVITY) AS DIFFERENCE;


-- =========================================================
-- SECTION 4: BASIC VALIDATION
-- =========================================================

SELECT
    COUNT(*) AS COMPONENT_WINDOW_ROWS
FROM COMPONENT_WINDOW_ACTIVITY;


SELECT
    COUNT(DISTINCT COMPONENT) AS UNIQUE_COMPONENTS,
    MIN(WINDOW_START) AS FIRST_WINDOW,
    MAX(WINDOW_END) AS LAST_WINDOW
FROM COMPONENT_WINDOW_ACTIVITY;


SELECT *
FROM COMPONENT_WINDOW_ACTIVITY
ORDER BY WINDOW_START, COMPONENT
LIMIT 30;


-- =========================================================
-- SECTION 5: COMPONENT HISTORY ANALYSIS
-- =========================================================

SELECT
    COMPONENT,
    COUNT(*) AS N_WINDOWS,
    SUM(EVENT_COUNT) AS TOTAL_EVENTS,
    ROUND(AVG(EVENT_COUNT), 2) AS AVG_EVENTS_PER_WINDOW,
    MEDIAN(EVENT_COUNT) AS MEDIAN_EVENTS_PER_WINDOW,
    MAX(EVENT_COUNT) AS MAX_EVENTS_PER_WINDOW,
    ROUND(STDDEV(EVENT_COUNT), 2) AS STDDEV_EVENTS
FROM COMPONENT_WINDOW_ACTIVITY
GROUP BY COMPONENT
ORDER BY N_WINDOWS DESC;


-- =========================================================
-- SECTION 6: HISTORY BUCKETS
-- =========================================================

SELECT
    CASE
        WHEN N_WINDOWS < 10 THEN '<10'
        WHEN N_WINDOWS < 20 THEN '10-19'
        WHEN N_WINDOWS < 50 THEN '20-49'
        ELSE '50+'
    END AS WINDOW_HISTORY_BUCKET,
    COUNT(*) AS COMPONENTS
FROM (
    SELECT
        COMPONENT,
        COUNT(*) AS N_WINDOWS
    FROM COMPONENT_WINDOW_ACTIVITY
    GROUP BY COMPONENT
)
GROUP BY WINDOW_HISTORY_BUCKET
ORDER BY
    CASE WINDOW_HISTORY_BUCKET
        WHEN '<10' THEN 1
        WHEN '10-19' THEN 2
        WHEN '20-49' THEN 3
        ELSE 4
    END;