USE WAREHOUSE PULSEOPS_WH;
USE DATABASE PULSEOPS;
USE SCHEMA CORE;

SHOW TABLES IN SCHEMA PULSEOPS.CORE;

SELECT LABEL, COUNT(*) AS BLOCK_COUNT
FROM GROUND_TRUTH_LABELS
GROUP BY LABEL
ORDER BY LABEL;

SELECT
    COUNT(*) AS TOTAL_LABEL_ROWS,
    COUNT(DISTINCT BLOCK_ID) AS DISTINCT_BLOCKS,
    COUNT_IF(BLOCK_ID IS NULL OR TRIM(BLOCK_ID) = '') AS BLANK_BLOCK_IDS,
    COUNT_IF(LABEL NOT IN ('Normal', 'Anomaly')) AS UNEXPECTED_LABELS
FROM GROUND_TRUTH_LABELS;
