USE ROLE ACCOUNTADMIN;
USE WAREHOUSE PULSEOPS_WH;
USE DATABASE PULSEOPS;
USE SCHEMA CORE;

TRUNCATE TABLE GROUND_TRUTH_LABELS;

COPY INTO GROUND_TRUTH_LABELS (BLOCK_ID, LABEL)
FROM (
    SELECT
        $1::STRING,
        $2::STRING
    FROM @PULSEOPS_UPLOAD_STAGE/anomaly_label.csv
)
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
)
ON_ERROR = 'ABORT_STATEMENT';