USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS PULSEOPS_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS PULSEOPS;

CREATE SCHEMA IF NOT EXISTS PULSEOPS.CORE;

USE WAREHOUSE PULSEOPS_WH;
USE DATABASE PULSEOPS;
USE SCHEMA CORE;