-- PulseOps Snowflake schema: single source of truth for all table DDL.
-- Safe to run before starting the streaming pipeline.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS PULSEOPS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS PULSEOPS;
CREATE SCHEMA IF NOT EXISTS PULSEOPS.CORE;

USE WAREHOUSE PULSEOPS_WH;
USE DATABASE PULSEOPS;
USE SCHEMA CORE;

-- ---------------------------------------------------------------------
-- Operational layer: populated directly by Spark or loaded once.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS RAW_LOG_EVENTS (
    RAW_LINE      STRING,
    LOG_DATE      STRING,
    LOG_TIME      STRING,
    PID           STRING,
    LEVEL         STRING,
    COMPONENT     STRING,
    MESSAGE       STRING,
    BLOCK_ID      STRING,
    EVENT_TIME    TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS WINDOWED_METRICS (
    WINDOW_START  TIMESTAMP_NTZ,
    WINDOW_END    TIMESTAMP_NTZ,
    BLOCK_ID      STRING,
    EVENT_COUNT   NUMBER,
    ERROR_COUNT   NUMBER,
    WARN_COUNT    NUMBER
);

CREATE TABLE IF NOT EXISTS INCIDENTS (
    WINDOW_START  TIMESTAMP_NTZ,
    WINDOW_END    TIMESTAMP_NTZ,
    BLOCK_ID      STRING,
    EVENT_COUNT   NUMBER,
    ERROR_COUNT   NUMBER,
    WARN_COUNT    NUMBER,
    IS_INCIDENT   BOOLEAN,
    DETECTED_AT   TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GROUND_TRUTH_LABELS (
    BLOCK_ID STRING,
    LABEL    STRING
);

CREATE OR REPLACE VIEW INCIDENT_EVIDENCE AS
SELECT
    i.BLOCK_ID,
    i.WINDOW_START,
    i.WINDOW_END,
    i.EVENT_COUNT,
    i.ERROR_COUNT,
    i.WARN_COUNT,
    r.LEVEL,
    r.COMPONENT,
    r.MESSAGE,
    r.EVENT_TIME
FROM INCIDENTS AS i
JOIN RAW_LOG_EVENTS AS r
  ON r.BLOCK_ID = i.BLOCK_ID
 AND r.EVENT_TIME >= i.WINDOW_START
 AND r.EVENT_TIME < i.WINDOW_END;

-- ---------------------------------------------------------------------
-- Analytical star layer.
-- These tables are rebuilt/refreshed by star_schema.sql. Their fact grain
-- is one row per block + incident window + component.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS DIM_BLOCK (
    BLOCK_KEY          NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    BLOCK_ID           STRING NOT NULL,
    GROUND_TRUTH_LABEL STRING,
    FIRST_SEEN_AT      TIMESTAMP_NTZ,
    LAST_SEEN_AT       TIMESTAMP_NTZ,
    CONSTRAINT PK_DIM_BLOCK PRIMARY KEY (BLOCK_KEY),
    CONSTRAINT UQ_DIM_BLOCK_ID UNIQUE (BLOCK_ID)
);

CREATE TABLE IF NOT EXISTS DIM_DATE (
    DATE_KEY     NUMBER NOT NULL,
    FULL_DATE    DATE NOT NULL,
    YEAR_NUMBER  NUMBER,
    QUARTER_NUMBER NUMBER,
    MONTH_NUMBER NUMBER,
    MONTH_NAME   STRING,
    DAY_NUMBER   NUMBER,
    DAY_OF_WEEK  STRING,
    IS_WEEKEND   BOOLEAN,
    CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_KEY)
);

CREATE TABLE IF NOT EXISTS DIM_COMPONENT (
    COMPONENT_KEY  NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    COMPONENT_NAME STRING NOT NULL,
    CONSTRAINT PK_DIM_COMPONENT PRIMARY KEY (COMPONENT_KEY),
    CONSTRAINT UQ_DIM_COMPONENT_NAME UNIQUE (COMPONENT_NAME)
);

CREATE TABLE IF NOT EXISTS FACT_INCIDENT_EVENTS (
    BLOCK_KEY             NUMBER NOT NULL,
    DATE_KEY              NUMBER NOT NULL,
    COMPONENT_KEY         NUMBER NOT NULL,
    WINDOW_START          TIMESTAMP_NTZ NOT NULL,
    WINDOW_END            TIMESTAMP_NTZ NOT NULL,
    COMPONENT_EVENT_COUNT NUMBER,
    COMPONENT_ERROR_COUNT NUMBER,
    COMPONENT_WARN_COUNT  NUMBER,
    WINDOW_EVENT_COUNT    NUMBER,
    WINDOW_ERROR_COUNT    NUMBER,
    WINDOW_WARN_COUNT     NUMBER,
    IS_INCIDENT           BOOLEAN,
    IS_TRUE_POSITIVE      BOOLEAN,
    LOADED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT FK_FACT_BLOCK FOREIGN KEY (BLOCK_KEY) REFERENCES DIM_BLOCK(BLOCK_KEY),
    CONSTRAINT FK_FACT_DATE FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    CONSTRAINT FK_FACT_COMPONENT FOREIGN KEY (COMPONENT_KEY) REFERENCES DIM_COMPONENT(COMPONENT_KEY)
);
